### ISSUE TITLE
Optimize performance by reusing instances of `PayFeed` from memory

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-gravityforms#37]
At yesterday's Pronamic Pay launch I came across this commit: fa89eaba746000d5c432b480f1b4f0b4b8e07994. I therefore did not dare to launch a new release of this library, because an issue/PR was missing. Do you remember what prompted these changes @rvdsteege? Are the changes complete or is this still work-in-progress?

**Comment by rvdsteege** [comment]
Yes, this is complete. I noticed a lot of duplicate queries in Query Monitor due to the payment feeds being instantiated multiple times. I thought we could improve on this by reusing the payment feeds.
